### ISSUE TITLE
Cannot download GFIE_dataset from Google Drive

### ISSUE THREAD

**Issue by Momofil31** [nkuhzx/GFIE#2]
Hi,
It seems that Google Drive is limiting the downloads for your dataset. Indeed `gdown https://drive.google.com/drive/folders/1AKA1jCVdrMmLIXqTeNNCFo5VnUrAcplq -O GFIE_dataset --folder` returns the error:

```
Access denied with the following error:

        Too many users have viewed or downloaded this file recently. Please
        try accessing the file again later. If the file you are trying to
        access is particularly large or is shared with many people, it may
        take up to 24 hours to be able to view or download the file. If you
        still can't access a file after 24 hours, contact your domain
        administrator.
```

It would be nice if you could provide a different mirror for downloading the dataset.

Thank you

**Comment by nkuhzx** [comment]
Thanks for the report, another mirror is being prepared, stay tuned.
We will let you know once the link is available.

**Comment by nkuhzx** [comment]
Hi, we have provided another way to download the data set. You can refer to the readme to run the shell script.

**Comment by nkuhzx** [comment]
Hi, we have provided another way to download the data set. You can refer to the readme to run the shell script.
