### ISSUE TITLE
GFIE dataset download path does not include the "rgb.zip" folder

### ISSUE THREAD

**Issue by ShijingWang9962** [nkuhzx/GFIE#3]
Dear author, I would like to inquire about the GFIE dataset. It seems that the download path does not include the "rgb.zip" folder？

**Comment by hyq217** [comment]
Dear author, 
Thanks for your brilliant research. I also have the same question, could you please help us to figure it out? 
Many thanks.
Best Regards

**Comment by wenzhengzeng** [comment]
I have the same question. Looking forward to the solution!

**Comment by nkuhzx** [comment]
We have reopened the download link for Google Cloud Drive, but the number of downloads may still be limited.
So we have also provided another way to download the data set. You can refer to the readme to run the shell script.
